---
- name: Create a project in OCP
  hosts: localhost
  connection: local
  gather_facts: no


  vars:
    ocp_host: 
    ocp_api_key: 

    refresh_miq: false
    miq_server:
    miq_provider_id:
    miq_username: admin
    miq_password: smartvm

    project_name: 

  tasks:        
    - name: Create "{{ project_name }}" Project
      openshift_raw:
        host: "{{ ocp_host }}"
        api_key: "{{ ocp_api_key }}"
        verify_ssl: no
        api_version: v1
        kind: Project
        name: "{{ project_name }}"
        # description: Testing
        # display_name: "This is a test project."
        state: present

    - name: Create "{{ project_name }}" Quota
      openshift_raw:
        host: "{{ ocp_host }}"
        api_key: "{{ ocp_api_key }}"
        verify_ssl: no
        namespace: "{{ project_name }}"
        state: present
        definition:
          apiVersion: v1
          kind: ResourceQuota
          metadata:
            name: compute-resources
          spec:
            hard:
              requests.cpu: "{{ requests_cpu }} " 
              requests.memory: "{{ requests_memory }}Gi"
              limits.cpu: "{{ limits_cpu }}" 
              limits.memory: "{{ limits_memory }}Gi"
          
    - name: Refresh MIQ provider
      uri:
        url: "https://{{ miq_server }}/api/providers/{{ miq_provider_id }}"
        method: POST
        user: "{{ miq_username }}"
        password: "{{ miq_password }}"
        body: {"action" : "refresh"}
        body_format: json
        validate_certs: false
      when: refresh_miq == true
